# Generated by Django 5.1.7 on 2025-03-08 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesibilitatRespiratoria',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Punt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altitud', models.FloatField()),
                ('index_qualitat_aire', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('correu', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('estat', models.CharField(max_length=255)),
                ('punts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Amistat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inici', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apuntat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignaAccesibilitatRespiratoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignaDificultatEsportiva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bloqueig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contaminant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('informacio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DificultatEsportiva',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventDeCalendari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('descripció', models.TextField()),
                ('data_inici', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estat', models.CharField(choices=[('pendent', 'Pendent'), ('resolta', 'Resolta')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Missatge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Presencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_recompensa', models.DateTimeField(auto_now_add=True)),
                ('punts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('nom', models.CharField(max_length=255)),
                ('dist_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacio', models.IntegerField()),
                ('comentari', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Xat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitatCultural',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.punt')),
                ('nom_activitat', models.CharField(max_length=255)),
                ('descripcio', models.CharField(max_length=255)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
            ],
            bases=('app.punt',),
        ),
        migrations.CreateModel(
            name='EstacioQualitatAire',
            fields=[
                ('punt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.punt')),
                ('nom_estacio', models.CharField(max_length=255)),
                ('descripcio', models.CharField(max_length=255)),
            ],
            bases=('app.punt',),
        ),
        migrations.AddConstraint(
            model_name='punt',
            constraint=models.UniqueConstraint(fields=('latitud', 'longitud', 'altitud'), name='punt_unic'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuari_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuari')),
            ],
            bases=('app.usuari',),
        ),
        migrations.AddField(
            model_name='amistat',
            name='accepta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptades', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='amistat',
            name='solicita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitades', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='apuntat',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuari'),
        ),
        migrations.AddField(
            model_name='assignaaccesibilitatrespiratoria',
            name='accesibilitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accesibilitatrespiratoria'),
        ),
        migrations.AddField(
            model_name='bloqueig',
            name='bloqueja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloquejants', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='bloqueig',
            name='bloquejat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloquejats', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='assignadificultatesportiva',
            name='dificultat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dificultatesportiva'),
        ),
        migrations.CreateModel(
            name='EventDeCalendariPrivat',
            fields=[
                ('eventdecalendari_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.eventdecalendari')),
            ],
            bases=('app.eventdecalendari',),
        ),
        migrations.CreateModel(
            name='EventDeCalendariPublic',
            fields=[
                ('eventdecalendari_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.eventdecalendari')),
                ('limit', models.IntegerField()),
            ],
            bases=('app.eventdecalendari',),
        ),
        migrations.AddField(
            model_name='eventdecalendari',
            name='creador_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuari'),
        ),
        migrations.AddField(
            model_name='invitacio',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacions_enviades', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='invitacio',
            name='destinatari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitacions_recibides', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='missatge',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missatges_autors', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='presencia',
            name='contaminant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contaminant'),
        ),
        migrations.AddField(
            model_name='presencia',
            name='punt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.punt'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuari'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('dist_km__gte', 0)), name='dist_km_valid'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AddField(
            model_name='assignadificultatesportiva',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AddField(
            model_name='assignaaccesibilitatrespiratoria',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AddField(
            model_name='valoracio',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ruta'),
        ),
        migrations.AddField(
            model_name='valoracio',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuari'),
        ),
        migrations.CreateModel(
            name='XatGrupal',
            fields=[
                ('xat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.xat')),
                ('descripció', models.TextField()),
            ],
            bases=('app.xat',),
        ),
        migrations.CreateModel(
            name='XatIndividual',
            fields=[
                ('xat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.xat')),
            ],
            bases=('app.xat',),
        ),
        migrations.AddField(
            model_name='missatge',
            name='xat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xat'),
        ),
        migrations.AddConstraint(
            model_name='activitatcultural',
            constraint=models.CheckConstraint(condition=models.Q(('data_inici__lte', models.F('data_fi'))), name='activitat_data_inici_menor_data_fi'),
        ),
        migrations.AddField(
            model_name='usuari',
            name='deshabilitador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.admin'),
        ),
        migrations.AddField(
            model_name='assignadificultatesportiva',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin'),
        ),
        migrations.AddField(
            model_name='assignaaccesibilitatrespiratoria',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin'),
        ),
        migrations.AddConstraint(
            model_name='amistat',
            constraint=models.UniqueConstraint(fields=('solicita', 'accepta'), name='amistat_unic'),
        ),
        migrations.AddConstraint(
            model_name='amistat',
            constraint=models.CheckConstraint(condition=models.Q(('data_inici__lte', models.F('data_final'))), name='data_inici_menor_data_final'),
        ),
        migrations.AddConstraint(
            model_name='bloqueig',
            constraint=models.UniqueConstraint(fields=('bloqueja', 'bloquejat'), name='bloqueig_unic'),
        ),
        migrations.AddField(
            model_name='eventdecalendariprivat',
            name='xat_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.xat'),
        ),
        migrations.AddConstraint(
            model_name='eventdecalendaripublic',
            constraint=models.CheckConstraint(condition=models.Q(('limit__gte', 0)), name='limit_valid'),
        ),
        migrations.AddField(
            model_name='apuntat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventdecalendaripublic'),
        ),
        migrations.AddConstraint(
            model_name='eventdecalendari',
            constraint=models.CheckConstraint(condition=models.Q(('data_inici__lte', models.F('data_fi'))), name='event_data_inici_menor_data_fi'),
        ),
        migrations.AddConstraint(
            model_name='presencia',
            constraint=models.UniqueConstraint(fields=('punt', 'contaminant', 'data'), name='presencia_unic'),
        ),
        migrations.AddConstraint(
            model_name='presencia',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='valor_valid'),
        ),
        migrations.AddConstraint(
            model_name='recompensa',
            constraint=models.UniqueConstraint(fields=('usuari', 'data_recompensa'), name='recompensa_unic'),
        ),
        migrations.AddConstraint(
            model_name='valoracio',
            constraint=models.UniqueConstraint(fields=('usuari', 'ruta'), name='valoracio_unic'),
        ),
        migrations.AddConstraint(
            model_name='valoracio',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacio__gte', 0), ('puntuacio__lte', 5)), name='puntuacio_valida'),
        ),
        migrations.AddField(
            model_name='xatgrupal',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xats_creadors', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='xatgrupal',
            name='membres',
            field=models.ManyToManyField(related_name='xats_membres', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='invitacio',
            name='xat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xatgrupal'),
        ),
        migrations.AddField(
            model_name='xatindividual',
            name='usuari1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xats_com_usuari1', to='app.usuari'),
        ),
        migrations.AddField(
            model_name='xatindividual',
            name='usuari2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xats_com_usuari2', to='app.usuari'),
        ),
        migrations.AddConstraint(
            model_name='assignadificultatesportiva',
            constraint=models.UniqueConstraint(fields=('usuari', 'ruta'), name='assigna_dificultat_unic'),
        ),
        migrations.AddConstraint(
            model_name='assignaaccesibilitatrespiratoria',
            constraint=models.UniqueConstraint(fields=('usuari', 'ruta'), name='assigna_accesibilitat_unic'),
        ),
        migrations.AddConstraint(
            model_name='apuntat',
            constraint=models.UniqueConstraint(fields=('usuari', 'event'), name='apuntat_unic'),
        ),
        migrations.AddConstraint(
            model_name='invitacio',
            constraint=models.UniqueConstraint(fields=('destinatari', 'xat'), name='invitacio_unic'),
        ),
    ]
