# Generated by Django 5.1.7 on 2025-03-18 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_run', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='punt',
            name='punt_unic',
        ),
        migrations.AddField(
            model_name='ruta',
            name='punts',
            field=models.ManyToManyField(related_name='rutes', to='app.punt'),
        ),
        migrations.AlterField(
            model_name='punt',
            name='altitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='punt',
            name='index_qualitat_aire',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='punt',
            constraint=models.UniqueConstraint(fields=('latitud', 'longitud'), name='punt_unic'),
        ),
    ]
