# Generated by Django 5.1.7 on 2025-03-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobexecution_remove_punt_punt_unic_ruta_punts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
