# Generated by Django 5.1.7 on 2025-03-20 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuari_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='punts',
        ),
        migrations.AddField(
            model_name='ruta',
            name='punt_inici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutes', to='app.punt'),
        ),
    ]
