# Generated by Django 5.1.7 on 2025-03-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ruta_punts_ruta_punt_inici'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contaminant',
            constraint=models.UniqueConstraint(fields=('nom',), name='nom_contaminant_unic'),
        ),
    ]
