# Generated by Django 5.1.5 on 2025-04-03 15:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contaminant_nom_contaminant_unic'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexQualitatAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valors_intervals', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contaminant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contaminant',), name='valoracio_contaminant_unic')],
            },
        ),
    ]
