# Generated by Django 5.1.7 on 2025-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_indexqualitataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punt',
            name='altitud',
        ),
        migrations.RemoveField(
            model_name='xat',
            name='nom',
        ),
        migrations.AddField(
            model_name='xatgrupal',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
