# Generated by Django 5.1.5 on 2025-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_punt_altitud_remove_xat_nom_xatgrupal_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='amistat',
            name='pendent',
            field=models.BooleanField(default=True),
        ),
    ]
