# Generated by Django 5.1.7 on 2025-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_amistat_pendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencia',
            name='valor_iqa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presencia',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
