# Generated by Django 5.1.5 on 2025-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_presencia_valor_iqa_alter_presencia_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuari",
            name="administrador",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
