# Generated by Django 5.1.5 on 2025-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_ruta_imatge_usuari_imatge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruta",
            name="imatge",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="usuari",
            name="imatge",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
    ]
