# Generated by Django 5.1.5 on 2025-05-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_delete_jobexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdecalendari",
            name="public",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
