name: Actualitzar BD

on:
    push:
      branches: [dev-dades-obertes-sense-middlewares]
    schedule:
      - cron: "55 5 * * 1"  # Cada lunes a les 5:55 UTC
    workflow_dispatch: 

jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - name: Crida a l'endpoint de trigger
              run: |
                curl -X POST https://airelliure-backend.onrender.com/actualitzar/rutes \
                     -H "Authorization: Bearer ${{ secrets.UPDATE_TOKEN }}"