name: Actualitzar BD

on:
    schedule:
      - cron: "5 6 * * *"  # Cada dia a les 6:00 UTC
    workflow_dispatch: 

jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - name: Crida a l'endpoint de trigger
              run: |
                curl -X POST https://airelliure-backend.onrender.com/actualitzar/estacions_qualitat_aire \
                     -H "Authorization: Bearer ${{ secrets.UPDATE_TOKEN }}"