name: Deploy to Render

on:
  workflow_run:
    workflows: ["Lint Code", "Run Tests"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
#      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"