name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: aire_lliure_db_user
          POSTGRES_PASSWORD: 0bdWMTSCRAEkzHb3xS8H0k4QZHBSops1
          POSTGRES_DB: aire_lliure_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://aire_lliure_db_user:0bdWMTSCRAEkzHb3xS8H0k4QZHBSops1@localhost:5432/aire_lliure_db
      DJANGO_SETTINGS_MODULE: AireLliure.settings
      PYTHON_VERSION: 3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest